import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Userprovider from "./components/Userprovider";

const jose = Josefin_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Todo Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${jose.className} h-screen bg-very-dark-blue`} suppressHydrationWarning>
        <Userprovider>{children}</Userprovider>
      </body>
    </html>
  );
}
